// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlVluF5OhKuUw8gol7GfKYGcL-Mb_nmE8',
    appId: '1:226645900971:android:84810eda5b1760f23ac1ee',
    messagingSenderId: '226645900971',
    projectId: 'restart-378613',
    storageBucket: 'restart-378613.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ9Dl7Y-Km_JqV_YYix25sxhFUIeUWU3U',
    appId: '1:226645900971:ios:06429070473d45bf3ac1ee',
    messagingSenderId: '226645900971',
    projectId: 'restart-378613',
    storageBucket: 'restart-378613.appspot.com',
    androidClientId: '226645900971-4133lgm20c5869d9cf9btno1l7uato6n.apps.googleusercontent.com',
    iosClientId: '226645900971-khrssht8c5p92987ul9lprvkch43fso9.apps.googleusercontent.com',
    iosBundleId: 'com.reStart.user',
  );
}
